[package]
name = "vibi"
version = "0.1.0"
authors = ["Nick Sanders <nsan1129@gmail.com>"]

[dependencies.bismit]
path = "/home/nick/projects/bismit"

[dependencies.time]
git = "https://github.com/rust-lang/time.git"

[dependencies]
# -- 0.12 currently required  to work with glium_text -- yeah wtf...
rand = "*"
glium = "0.13"
glium_text = "*"
image = "*"
find_folder = "*"
# elmesque = "*"
num = "*"
vecmath = "*"
rustc-serialize = "*"

# piston_window = "*"
# piston2d-opengl_graphics = "*"
# conrod = "0.23"
# piston = "0.16.0"
# pistoncore-glutin_window = "0.20.0"
# piston-viewport = "0.2.0"
# piston2d-gfx_graphics = "0.13.0"
# gfx = "0.8.1"
# cgmath = "*"

